In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

In [4]:
X,y = make_classification(n_samples = 1000, n_features = 3, n_redundant = 1, n_classes = 2, random_state = 999)

In [5]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]], shape=(1000, 3))

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33 , random_state = 42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, algorithm = 'auto') #by default it will take p value = 2 means eucledian distance

In [10]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)


In [11]:
from sklearn.metrics import confusion_matrix , accuracy_score, classification_report

In [12]:
print(confusion_matrix(y_pred,y_test))

[[158  20]
 [ 11 141]]


In [13]:
print(accuracy_score(y_pred,y_test))

0.906060606060606


In [14]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      0.89      0.91       178
           1       0.88      0.93      0.90       152

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [18]:
classifier = KNeighborsClassifier(n_neighbors = 7, algorithm = 'auto')

In [19]:
print(confusion_matrix(y_pred,y_test))

[[158  20]
 [ 11 141]]


In [20]:
print(accuracy_score(y_pred,y_test))

0.906060606060606


In [21]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      0.89      0.91       178
           1       0.88      0.93      0.90       152

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330

